services:
  - type: web
    name: stremio-nuvio-kra-addon
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node bootstrap.cjs
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 20.19.5
      - key: CONFIG_SECRET
        generateValue: true
      - key: DEBUG
        value: 0
      - key: UPSTREAM_STREMIO_BASE
        sync: false
